function spikeStruct = CreateSpikeStruct( numEvents )
  
  nanList = NaN( 1, numEvents );
  doubleNanList = NaN( 2, numEvents );
  spikeStruct = struct( 'spikeWaveforms', [], 'spikeInitIndex', nanList, ...
    'spikeTimeMs', nanList, ...
    'spikeThreshold', nanList, 'height', nanList, 'riseTime', nanList, ...
    'decayTime', nanList, ...
    'AP10', nanList, 'AP10_TimesMs', doubleNanList, 'AP10_Voltage', nanList, ...
    'AP20', nanList, 'AP20_TimesMs', doubleNanList, 'AP20_Voltage', nanList, ...
    'AP50', nanList, 'AP50_TimesMs', doubleNanList, 'AP50_Voltage', nanList, ...
    'AP80', nanList, 'AP80_TimesMs', doubleNanList, 'AP80_Voltage', nanList, ...
    'AP90', nanList, 'AP90_TimesMs', doubleNanList, 'AP90_Voltage', nanList, ...
    'spikePeak', nanList, ...
    'preMaxDeriv', nanList, 'preMaxDerivTimes', nanList, ...
    'preMaxConcavity', nanList, 'preMaxConcavityTime', nanList, ...
    'preMinConcavity', nanList, 'preMinConcavityTime', nanList, ...
    'postMinDeriv', nanList, 'postMinDerivTime', nanList, ...
    'postMaxConcavity', nanList, 'postMaxConcavityTime', nanList, ...
    'fAHP', nanList, 'fAHPTime', nanList, 'fAHPAbsolute', nanList, ...
    'mAHP', nanList, 'mAHPTime', nanList, 'mAHPAbsolute', nanList );

end