function spikeStruct = CreateSpikeStruct( numEvents )
  
  nanList = NaN( 1, numEvents );
  spikeStruct = struct( 'spikeWaveforms', [], 'spikeInitIndex', nanList, ...
    'spikeTimeMs', nanList, ...
    'spikeThreshold', nanList, 'height', nanList, 'riseTime', nanList, ...
    'decayTime', nanList, 'AP10', nanList, 'AP20', nanList, 'AP50', nanList, ...
    'AP80', nanList, 'AP90', nanList, 'spikePeak', nanList, ...
    'preMaxDeriv', nanList, 'preMaxDerivTimes', nanList, ...
    'preMaxConcavity', nanList, 'preMaxConcavityTime', nanList, ...
    'preMinConcavity', nanList, 'preMinConcavityTime', nanList, ...
    'postMinDeriv', nanList, 'postMinDerivTime', nanList, ...
    'postMaxConcavity', nanList, 'postMaxConcavityTime', nanList, ...
    'fAHP', nanList, 'fAHPTime', nanList, 'fAHPAbsolute', nanList, ...
    'mAHP', nanList, 'mAHPTime', nanList, 'mAHPAbsolute', nanList );

end